# https://tauri.app/v1/api/config

# https://tauri.app/v1/api/config#packageconfig
[package]
productName = "lighting"
version = "0.1.0"


# https://tauri.app/v1/api/config#tauriconfig
[tauri]

[tauri.bundle]
active = true
targets = "all"
identifier = "com.lighting.dev"
icon = [
  "assets/icons/32x32.png",
  "assets/icons/128x128.png",
  "assets/icons/128x128@2x.png",
  "assets/icons/icon.icns",
  "assets/icons/icon.ico",
]

[tauri.security]
csp = "null"

[[tauri.windows]]
center = true
width = 800
height = 600
resizable = true
title = "lighting"
fullscreen = false


# https://tauri.app/v1/api/config#buildconfig
[build]
beforeDevCommand = "cargo watch -w lighting-frontend -- trunk serve --config lighting-frontend/Trunk.toml"
beforeBuildCommand = "trunk build --config lighting-frontend/Trunk.toml"
devPath = "http://localhost:1420"
distDir = "../dist"
withGlobalTauri = true


# https://tauri.app/v1/api/config#pluginconfig
[plugins]
